---

- hosts: all
  become: yes
  roles:
    - role: basic

- hosts: virtual
  become: yes
  roles:
    - role: virtual

- hosts: pier8
  become: yes
  roles:
    - role: docker

- hosts: kube
  become: yes
  vars:
    master_ip: 10.8.0.65
  roles:
    - role: docker
    - role: kube
