---
- name: Add the admin users with a bash shell, appending the group 'sudo' to the user's groups
  user:
    name: "{{ item }}"
    shell: /bin/bash
    groups: sudo
    append: yes
  with_items:
   - manyos
   - rhannemann
    
- name: Set authorized keys taken from url for admin user admin
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "https://raw.githubusercontent.com/manyosit/ansible/master/ssh-keys/{{ item }}"
  with_items:
   - manyos
   - rhannemann

- name: Allow passwordless Sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
