---

- name: "set hostnames"
  hostname:
    name: "{{ inventory_hostname}}"

- name: Install guest agent
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'qemu-guest-agent']

- name: enable guest agent service
  systemd:
    name: qemu-guest-agent
    state: started
    enabled: True
